version: '3.3'

services:
  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: zhdanova686/foodgram_backend:latest
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata initial_data.json &&
             python manage.py collectstatic --noinput &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: zhdanova686/foodgram_frontend:latest
    volumes:
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/

  nginx:
    image: nginx:1.21
    volumes:
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
