name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_backend:buildcache,mode=max

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:buildcache,mode=max

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/foodgram
            docker compose pull
            docker compose down
            docker compose up -d
            docker system prune -f 